### DISCUSSION TITLE
SNIA SDC 2024 Demo Materials

### DISCUSSION THREAD

**Discussion by phlogistonjohn** [samba-in-kubernetes/samba-container#178] [Show and tell]
Background, scripts, and files related to John and Guenther's presentation for SDC 2024.

## Prerequisites

* 5 node Ceph cluster
* At least 3 OSDs (1 per node) already created
* 1 Active Directory Domain Controller
* 1 Linux Client (optional)
* 1 Windows Client - joined to above AD DC
* 3 unused & available IP addresses on a subnet reachable by the client nodes

Ceph cluster can be installed just prior to this procedure.
Windows client may need additional time to join to AD, we used the AD DC from samba-container project with a default configuration.

Copy the contents of `cluster2.yaml` to the ceph admin node. Content below.

### SMB Module and filesystem
* Enable smb module: `ceph mgr module enable smb`
* Create a cephfs file system: `ceph fs volume create cephfs`
* Create a cephfs subvolume group: `ceph fs subvolumegroup create cephfs demos`
* Create 4 cephfs subvolumes: `for sub in uv1 uv2 domv1 domv2 ; do ceph fs subvolume create cephfs --group-name=demos --sub-name=$sub --mode=0777 ;  done`

### Host labeling
* Label one cluster node “first”: `ceph orch host label add ceph0 first`
* Label three other cluster nodes “cs2” (no overlapping labels):
  * ceph orch host label add ceph2 cs2
  * ceph orch host label add ceph3 cs2
  * ceph orch host label add ceph4 cs2

We label the host nodes this way to make it easy to determine where the smb services will be placed later on. This is not always going to be necessary for general use.

## First Cluster

* The ceph smb module has two modes of operation: an imperative set of commands and
a declarative set of resource descriptions
* Both work equally well. The imperative set of commands will be familiar to someone who
has used Ceph’s NFS module before
* The declarative mode is similar to the service specifications that one can use with
Cephadm orchestration
* Let’s start with a very simple set of imperative commands
* `ceph smb cluster ls` - there should be no clusters yet
* To define a cluster: `ceph smb cluster create starter user --define-user-pass=test%D3m0123 --define-user-pass=test2%0th3rD3m0 --placement=’1 label:first`
* Now that we have a cluster we can define some new shares:
  * `ceph smb share create starter share1 --cephfs-volume=cephfs --subvolume=demos/uv1 --path=/`
  * `ceph smb share create starter share2 --cephfs-volume=cephfs --subvolume=demos/uv2 --path=/ --share-name='Share Two'`
* The commands that we just ran all created resources within the ceph smb mgr module. We can see them with `ceph smb show`
* You can limit the show command to only certain resources or resource types. Let’s look at just our shares: `ceph smb show ceph.smb.share`  or just one specific cluster `ceph smb show  ceph.smb.cluster.starter --format=yaml`
* Run `ceph orch ls` to show a running services, including a new smb service

### Quick CLI Test

We can do a quick test using Samba's `smbclient` tool. It's fast to use but you can skip this step or use a windows client if desired.

* `smbclient -U ‘test%D3m0123’ ∕∕192.168.76.200∕share1`
* `smbclient -U ‘test2%0th3rD3m0’ ∕∕192.168.76.200∕share1`
* `smbclient -U ‘test2%0th3rD3m0’ ∕∕192.168.76.200∕"Share Two"`

## Second Cluster

This cluster will be installed using the "declarative method". We define everything we need to set up our cluster: cluster settings, shares, and domain join authentication info in a single yaml file we'll call `cluster2.yaml`:

```yaml
resources:
  # Cluster settings
  - resource_type: ceph.smb.cluster
    cluster_id: ccad
    auth_mode: active-directory
    domain_settings:
      realm: DOMAIN1.SINK.TEST
      join_sources:
        - source_type: resource
          ref: join1-admin
    custom_dns: [192.168.76.210]
    public_addrs:
      - address: 192.168.76.50/24
      - address: 192.168.76.51/24
      - address: 192.168.76.52/24
    placement:
      count: 3
      label: cs2
  # Auth info needed to join
  - resource_type: ceph.smb.join.auth
    auth_id: join1-admin
    auth:
      username: Administrator
      password: Passw0rd
  # Shares
  - resource_type: ceph.smb.share
    cluster_id: ccad
    share_id: cshare
    name: Cluster Share One
    cephfs:
      volume: cephfs
      subvolumegroup: demos
      subvolume: domv1
      path: /
  - resource_type: ceph.smb.share
    cluster_id: ccad
    share_id: ufiles
    name: Useful Files
    cephfs:
      volume: cephfs
      subvolumegroup: demos
      subvolume: domv2
      path: /
```

This YAML file defines a cluster that will use both Active Directory and Clustering. Samba's clustering system, CTDB, will manage the supplied public IP Addresses.

* Load the resources into ceph: `ceph smb apply  -i - < cluster2.yaml`
* View the new smb service is starting `ceph orch ls`
* This may take a moment so we can look at the new resources we just created:
  * `ceph smb show ceph.smb.cluster --format=yaml`
  * `ceph smb show ceph.smb.cluster.ccad --format=yaml`
* Eventually, `ceph orch ls` should show `3/3` daemons running and we're ready to test client access.

## Windows Client

From the windows client, log into `\\192.168.76.50\Cluster Share One`,  where the IP address is any of the public IP addresses from the YAML spec. We can read and write files to the shares.

Log into `\\192.168.76.200\share1` (using the IP of the first cluster node). This should prompt for login. Provide the settings of one of the deinfed users with cluster `starter`.

## Deleting a Cluster

* Run `ceph smb cluster ls` to list clusters
* Run `ceph smb share ls starter` to list shares belonging to the starter cluster
* Run `ceph smb share rm starter share1` to delete the first share
* Run `ceph smb share rm starter share2` to delete the second share
* Run `ceph orch ls` to show the two clusters are still running
* Run `ceph smb cluster rm starter` to remove the cluster
* Run `ceph orch ls` to show that the first cluster has been deleted
