### ISSUE TITLE
How to run with podman compose?

### ISSUE THREAD

**Issue by vwkd** [samba-in-kubernetes/samba-container#173]
I'm trying to run a simple Samba share with podman on Fedora and access it from Finder on macOS.

However, Finder always indicates that username and password are incorrect by wiggling the window. The server address is correct and reachable, otherwise it would show an explicit error popup.

It seems neither a custom login in the config nor the default login with username `sambauser` and password `samba` work, which can be tested by commenting out the `SAMBACC_CONFIG` in the `docker-compose.yml`.

I'm running into more difficulties with the config file as well, leading me to suspect the config might be buggy. For example, customizing the `configs.demo` or `shares.share` keys in the config file or providing the `SAMBA_CONTAINER_ID` environment variable (that supposedly should match the `configs.demo` key?) in the compose file each throw an error.

It would be great if a minimal podman compose setup could be documented.

## Steps To Reproduce

1. Create `docker-compose.yml`

```yml
version: "3"

services:
  samba:
    image: quay.io/samba.org/samba-server:latest
    environment:
      SAMBACC_CONFIG=/usr/local/etc/config.json
      # throws if uncommented!
      # SAMBA_CONTAINER_ID=demo
    restart: unless-stopped
    volumes:
    - ./data:/shares/foobar:Z
    - ./config:/usr/local/etc:Z
    ports:
    - "4450:445"
```

2. Create `config/config.json`

```json
{
  "samba-container-config": "v0",
  "configs": {
    "demo": {
      "instance_name": "SAMBA",
      "shares": [
        "share"
      ],
      "globals": [
        "default"
      ]
    }
  },
  "shares": {
    "share": {
      "options": {
        "path": "/share",
        "valid users": "foobar",
        "writeable": "yes"
      }
    }
  },
  "globals": {
    "default": {
      "options": {
        "server min protocol": "SMB3",
        "server smb encrypt": "required",
        "load printers": "no",
        "printing": "bsd",
        "printcap name": "/dev/null",
        "disable spoolss": "yes"
      }
    }
  },
  "users": {
    "all_entries": [
      {
        "name": "foobar",
        "password": "foobar"
      }
    ]
  },
  "_footer": 1
}
```

3. Run `podman compose up`
4. In macOS Finder open `Connect to Server...` for `smb://server-ip:4450`

## Versions

- podman 5.0.3
- Fedora 40
- macOS 14.5

**Comment by phlogistonjohn** [comment]
> For example, customizing the `configs.demo` or `shares.share` keys in the config file or providing the `SAMBA_CONTAINER_ID` environment variable (that supposedly should match the `configs.demo` key?) in the compose file each throw an error.

Could you please provide examples of these errors?


There are some docker compose examples here: https://github.com/samba-in-kubernetes/samba-container/discussions/130
These do include a bunch of stuff you may wish to ignore, like an AD DC config.

I suspect your yaml syntax needs updating. Instead of:
```yaml
    environment:
      SAMBACC_CONFIG=/usr/local/etc/config.json
      # throws if uncommented!
      # SAMBA_CONTAINER_ID=demo
```
try
```yaml
    environment:
      SAMBACC_CONFIG: /usr/local/etc/config.json
      SAMBA_CONTAINER_ID: demo
```
