### ISSUE TITLE
Samba container fails to start due to lockfile conflict with separate Winbind container

### ISSUE THREAD

**Issue by NN708** [samba-in-kubernetes/samba-container#200]
When running Samba server as an Active Directory member with a separate Winbind container, the Samba service `smbd` fails to start due to a lockfile conflict.

### Steps to reproduce:
1. Create `docker-compose.yml`:

    ```yaml
    services:
      samba:
        image: quay.io/samba.org/samba-server:latest
        container_name: samba
        restart: unless-stopped
        ports:
          - 445:445
        volumes_from:
          - winbind
        volumes:
          - ./share:/share
        environment:
          SAMBACC_CONFIG: /etc/samba-container/config.yml
        depends_on:
          - winbind
        privileged: true

      winbind:
        image: quay.io/samba.org/samba-server:latest
        container_name: samba-winbind
        restart: unless-stopped
        volumes:
          - ./config:/etc/samba-container:ro
          - ./data:/var/lib/samba
          - ./socket:/run/samba/winbindd
        environment:
          SAMBACC_CONFIG: /etc/samba-container/config.yml
        command: ['run', 'winbindd']
    ```

2. Start containers: `docker compose up`

### Logs:
```
No builtin backend found, trying to load plugin
load_module_absolute_path: Module '/usr/lib64/samba/pdb/tdbsam.so' loaded
added interface eth0
smbd version 4.21.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2024
uid=0 gid=0 euid=0 egid=0
messaging_dgm_lockfile_create: fcntl failed: Resource temporarily unavailable
messaging_dgm_init: messaging_dgm_create_lockfile failed: Resource temporarily unavailable
messaging_dgm_ref failed: Resource temporarily unavailable
```

### Workaround:
Manually removing `./data/lock/msg.lock` allows the Samba container to start.

### Environment:
Container runtime: Podman 5.4.0

I'd appreciate any guidance on best practices for running Samba and Winbind in containers.
